server {
    listen 80;
    server_name 46.225.56.35;

    client_max_body_size 20M;

    location / {
        root /var/www/novia/frontend/dist;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /media/ {
        alias /var/www/novia/backend/media/;
    }

    location /static/ {
        alias /var/www/novia/backend/staticfiles/;
    }

    location ~ ^/(api|admin) {
        include proxy_params;
        proxy_pass http://unix:/run/novia.sock;
    }
}
